name: ${rootProject.name.capitalize()}
version: $version
main: $group.${rootProject.name}.plugin.${rootProject.name.capitalize()}Plugin
api-version: 1.17
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.5.21
  - org.jetbrains.kotlin:kotlin-reflect:1.5.21